/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseTable: typeof import('./../src/components/BaseTable/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    IconCustomLogo: typeof import('~icons/custom/logo')['default']
    IconEpEdit: typeof import('~icons/ep/edit')['default']
    IconMdiAccessPoint: typeof import('~icons/mdi/access-point')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
